server:
  error:
    include-stacktrace: on_param
  port: 8080
spring:
  #BD access
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  #update BD, log SQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #mail configuration
  mail:
    host: ${GMAIL_HOST}
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${GMAIL_TRUST}
#mail front-end
mail:
  url:
    front: ${FRONT_END_URL}
cross:
  origins: ${CROSS_ORIGIN_URL}
#security
jwt:
  secret: ${JWT_SECRET}
  expiration: 1000000
  refresh-secret: ${JWT_REFRESH_SECRET}
#cloud
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadaUtils: error